version: '3.8'
services:
  node_server:
    image: datadog-security-labs-pocs/node_server
    build: server
    hostname: node_server.local
    networks:
       default:    
          aliases:
            - node_server.local
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3000
    ports:
      - '3000:3000'
    networks:
      backend:
        ipv4_address: 172.20.0.2
  ossl_client:
    depends_on: 
      - node_server
    image: datadog-security-labs-pocs/ossl_client
    build: client
    environment:
      - HOSTNAME=172.20.0.2
      - PORT=3000
    networks:
      backend:
        ipv4_address: 172.20.0.3

networks:
  backend:
    ipam:
      config:
        - subnet: 172.20.0.0/24